module.exports = {
	maps: [`"0,Nacht Der Untoten,"Nacht Der Untoten" -prince -phillip -Mobile -where -what -who -when -how lang:en -filter:links -filter:replies -ZombiesBOT_ -Nachtsmoocher -Aether_ZHistory`,
`1,Verruckt,verruckt  zombies  -where -what -who -when -how lang:en -filter:links -filter:replies`,
`2,Shi No Numa,"Shi No Numa"  -where -what -who -when -how lang:en -filter:links -filter:replies -CODZombiesQuote -ZombiesBOT_`,
`3,Der Riese,"Der Riese" -"Im on" -WR -where -what -who -when -how lang:en -filter:links -filter:replies -CODZombiesQuote -ZombiesBOT_`,
`4,Kino Der Toten,"Kino Der Toten" -WR -where -what -who -when -how lang:en -filter:links -filter:replies -CODZombiesQuote -ZombiesBOT_`,
`5,Five,"FIVE" zombies ("Black Ops" OR "Black Ops Zombies") -stream -where -what -who -when -how -mode -WR -spent -years -CODZombiesQuote -ZombiesBOT_ -at lang:en -filter:links -filter:replies`,
`6,Ascension,Ascension (COD OR "Black Ops") -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`7,Call of the Dead,"Call of the Dead" (cotd OR map OR COD OR "Black Ops") -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`8,Shangri-La,"Shangri la" (zombies OR COD OR "Black Ops") -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`9,Moon,"Moon" Zombies (COD OR "Black Ops") -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`10,Tranzit,"Tranzit" -route -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ -ThatSEGABot lang:en -filter:links -filter:replies`,
`11,Nuketown,"Nuketown zombies" -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ -ThatSEGABot lang:en -filter:links -filter:replies`,
`12,Die Rise,"Die Rise" (Zombies OR BO2 OR "Black Ops") -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ -ThatSEGABot lang:en -filter:links -filter:replies`,
`13,Mob of the Dead,"Mob of the Dead" -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ -ThatSEGABot lang:en -filter:links -filter:replies`,
`14,Buried,"Buried" Zombies (COD OR "Black Ops") -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`15,Origins,"origins" zombies (COD OR "Black Ops") -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`16,Shadows of Evil,"Shadows of evil" -watch -video -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`17,Zetsubou No Shima,"Zetsubou No Shima" -live -cipher -top -EE -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`18,Der Eisendrache,"Der Eisendrache" -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`19,Gorod Krovi,"Gorod Krovi" -live -cipher -top -EE -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`20,Revelations,"revelations" zombies (COD OR "Black Ops") -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`21,Voyage of Despair,"Voyage of Despair" -live -cipher -top -EE -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`22,IX,"IX" zombies (COD OR "Black Ops") -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`23,Blood of the Dead,"blood of the dead" (zombies OR COD OR "Black Ops") -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`24,Classified,"classified" ("Black Ops 4" OR BO4) -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`25,Dead of the Night,"Dead of the Night" (zombies OR "Black Ops 4" OR BO4) -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`26,Ancient Evil,"Ancient Evil" (zombies OR "Black Ops" OR BO4) -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`27,Alpha Omega,"Alpha Omega" (zombies OR "Black Ops" OR BO4) -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`28,Tag der Toten,"tag der toten" -live -cipher -top -EE -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`29,Die Maschine,"Die Maschine" -live -cipher -top -EE -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -ZombiesBOT_ lang:en -filter:links -filter:replies`,
`30,Firebase Z,"Firebase Z" -live -cipher -top -EE -streaming -stream -where -what -who -when -how -WR -CODZombiesQuote -MittensBattle -ZombiesBOT_ lang:en -filter:links -filter:replies`]
}
